backend:
  name: github
  repo: nspilman/campnos-website
  branch: gatsby-setup

media_folder: static/assets
public_folder: /assets

collections:
  - name: bios
    label: bios
    folder: content/bios
    create: true
    fields:
      - { name: name, label: Name }
      - { name: twitter, label: Twitter }
      - { name: instagram, label: Instagram }
      - { name: image, label: Image, widget: image }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  - name: shows
    label: shows
    folder: content/shows
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: logo, label: Logo, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: episodes
    label: episodes
    folder: content/episodes
    create: true
    fields:
      - { name: title, label: Title }
      - { name: show, label: Show, widget: select, option: ["The NosCast","Greg's Awesome Party", "Prime Stories"] }
      - { name: date, label: Date, widget: datepicker }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }