backend:
  name: github
  repo: nspilman/campnos-website
  branch: gatsby-setup

media_folder: static/assets
public_folder: /assets

collections:
  - name: bios
    label: bios
    folder: content/bios
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  
  - name: shows
    label: categories
    folder: content/shows
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: episodes
    label: shows
    folder: content/episodes
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }